debug: ${SCIP_DEBUG:false}

logging:
  file:
    path: ${SCIP_LOGGING_FILE_PATH:/tmp}

server:
  address: 0.0.0.0
  port: 8080

spring:
  application:
    name: spring-cloud-in-practice-gateway
  redis:
    host: ${SCIP_SPRING_REDIS_HOST:localhost}
    port: ${SCIP_SPRING_REDIS_PORT:6379}
    password: ${SCIP_SPRING_REDIS_PASSWORD:}
    timeout: 1s
    lettuce:
      pool:
        max-wait: 1s
  session:
    timeout: 7d
    store-type: redis
    redis:
      namespace: scip:session
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    consul:
      host: ${SCIP_SPRING_CLOUD_CONSUL_HOST:localhost}
      port: ${SCIP_SPRING_CLOUD_CONSUL_PORT:8500}
      discovery:
        enabled: true
        register: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

service:
  file:
    base-url: ${SCIP_SERVICE_FILE_BASE_URL:http://localhost:8080/files}
  hydra:
    url: ${SCIP_SERVICE_HYDRA_URL:http://localhost:4444/}
    admin-url: ${SCIP_SERVICE_HYDRA_ADMIN_URL:http://localhost:4445/}
